// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYuiE13Py0TES8XtEl_Ozpok-l7J6ILI',
    appId: '1:84665289194:web:2fad8dc223cbc451734a93',
    messagingSenderId: '84665289194',
    projectId: 'my-cool-project-22-27',
    authDomain: 'my-cool-project-22-27.firebaseapp.com',
    storageBucket: 'my-cool-project-22-27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vsOPyMPH3w3h4z9YPyFHYDaxn0hTt0M',
    appId: '1:84665289194:android:6d78342fc75f6270734a93',
    messagingSenderId: '84665289194',
    projectId: 'my-cool-project-22-27',
    storageBucket: 'my-cool-project-22-27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVesh7r_5H3jRE997rzLHG8xdaMkJiitM',
    appId: '1:84665289194:ios:e504f7cb5a3e81c8734a93',
    messagingSenderId: '84665289194',
    projectId: 'my-cool-project-22-27',
    storageBucket: 'my-cool-project-22-27.firebasestorage.app',
    iosBundleId: 'com.example.myEduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVesh7r_5H3jRE997rzLHG8xdaMkJiitM',
    appId: '1:84665289194:ios:e504f7cb5a3e81c8734a93',
    messagingSenderId: '84665289194',
    projectId: 'my-cool-project-22-27',
    storageBucket: 'my-cool-project-22-27.firebasestorage.app',
    iosBundleId: 'com.example.myEduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgYuiE13Py0TES8XtEl_Ozpok-l7J6ILI',
    appId: '1:84665289194:web:31a2eae9277e27aa734a93',
    messagingSenderId: '84665289194',
    projectId: 'my-cool-project-22-27',
    authDomain: 'my-cool-project-22-27.firebaseapp.com',
    storageBucket: 'my-cool-project-22-27.firebasestorage.app',
  );

}