// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgLnWclrL5Dfe72eMPRhkOWiPmGEO_PE',
    appId: '1:622907104478:web:b7d739a1014273d27b364f',
    messagingSenderId: '622907104478',
    projectId: 'myeduapp-0411',
    authDomain: 'myeduapp-0411.firebaseapp.com',
    storageBucket: 'myeduapp-0411.firebasestorage.app',
    measurementId: 'G-246NHP5BXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphSTuxdi0za9rXUeo02xCDfr-GDRLvu8',
    appId: '1:622907104478:android:dbcf7ccd78d4bf4c7b364f',
    messagingSenderId: '622907104478',
    projectId: 'myeduapp-0411',
    storageBucket: 'myeduapp-0411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtfA2OsaPjJrFjRlVM7f3ojBNLBB-P-uk',
    appId: '1:622907104478:ios:48b8e1c16bf41dba7b364f',
    messagingSenderId: '622907104478',
    projectId: 'myeduapp-0411',
    storageBucket: 'myeduapp-0411.firebasestorage.app',
    iosBundleId: 'com.example.myEduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtfA2OsaPjJrFjRlVM7f3ojBNLBB-P-uk',
    appId: '1:622907104478:ios:48b8e1c16bf41dba7b364f',
    messagingSenderId: '622907104478',
    projectId: 'myeduapp-0411',
    storageBucket: 'myeduapp-0411.firebasestorage.app',
    iosBundleId: 'com.example.myEduApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgLnWclrL5Dfe72eMPRhkOWiPmGEO_PE',
    appId: '1:622907104478:web:64553264928bb53e7b364f',
    messagingSenderId: '622907104478',
    projectId: 'myeduapp-0411',
    authDomain: 'myeduapp-0411.firebaseapp.com',
    storageBucket: 'myeduapp-0411.firebasestorage.app',
    measurementId: 'G-LMWRF7KEVD',
  );
}
